name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check code style
        run: |
          pnpm prettier --check .
          pnpm eslint .

      - name: Build Check
        run: |
          pnpm build:weapp
          pnpm build:h5

      - name: Package Artifacts
        run: |
          cd dist
          zip -r weapp.zip weapp/
          zip -r h5.zip h5/

      - name: Upload WeApp Build
        uses: actions/upload-artifact@v3
        with:
          name: weapp-build
          path: dist/weapp.zip
          retention-days: 5
          if-no-files-found: error

      - name: Upload H5 Build
        uses: actions/upload-artifact@v3
        with:
          name: h5-build
          path: dist/h5.zip
          retention-days: 5
          if-no-files-found: error
